### ISSUE TITLE
Operand Replacement Operator ORO needs to obey types of operands.

### ISSUE THREAD

**Issue by sohah** [sohah/ContractDR#1]
ORO Mutation operator needs to account for type of operand that match the operator.

ORO Mutation operator produced  the following property, where `out_Highest_Level_Alarm` is int and original property is `p1 = (true -> ((System_On and Door_Open) =>  (out_Highest_Level_Alarm >= 3)));`

`node main(
  Commanded_Flow_Rate : int;
  Current_System_Mode : int;
  System_On : bool;
  System_Monitor_Failed : bool;
  Logging_Failed : bool;
  Infusion_Initiate : bool;
  Disable_Audio : int;
  Notification_Cancel : bool;
  VTBI_High : int;
  Flow_Rate_High : int;
  Flow_Rate_Low : int;
  Flow_Rate : int;
  Flow_Rate_Not_Stable : bool;
  Air_In_Line : bool;
  Occlusion : bool;
  Door_Open : bool;
  Temp : bool;
  Air_Pressure : bool;
  Humidity : bool;
  Battery_Depleted : bool;
  Battery_Low : bool;
  Battery_Unable_To_Charge : bool;
  Supply_Voltage : bool;
  CPU_In_Error : bool;
  RTC_In_Error : bool;
  Watchdog_Interrupted : bool;
  Memory_Corrupted : bool;
  Pump_Too_Hot : bool;
  Pump_Overheated : bool;
  Audio_Enable_Duration : int;
  Audio_Level : int;
  Config_Warning_Duration : int;
  Low_Reservoir : int;
  Max_Duration_Over_Infusion : int;
  Max_Duration_Under_Infusion : int;
  Max_Paused_Duration : int;
  Max_Idle_Duration : int;
  Tolerance_Max : int;
  Tolerance_Min : int;
  Reservoir_Empty : bool;
  Reservoir_Volume : int;
  Volume_Infused : int;
  In_Therapy : bool;
  Config_Timer : int;
  out_Is_Audio_Disabled : int;
  out_Notification_Message : int;
  out_Audio_Notification_Command : int;
  out_Highest_Level_Alarm : int;
  out_Log_Message_ID5 : int
) returns (
  p1 : bool
);
let
  --%MAIN;
  p1 = (true -> repair( ((out_Highest_Level_Alarm and Door_Open) => (out_Highest_Level_Alarm >= 3)) , repairNode(System_On, out_Highest_Level_Alarm, Door_Open) ) );

  --%PROPERTY p1;

tel;`

**Comment by vaibhavbsharma** [comment]
Where can I find the type information?

**Comment by vaibhavbsharma** [comment]
I've fixed this issue. We should now be producing fewer ORO mutants but only produce those operand replacement mutations where the old operand being substituted has a type that matches the type of the new operand that the old operand is substituted with.

**Comment by sohah** [comment]
I still see the issue happing with "<" operators with boolean operators.


The generated property was 

  p1 = repair( ((out < (a or (b and c))) or false) , repairNode(a, b, c, out) ) ;

ROR-0--1

the original property is:
p1 = out = (a or b and c) or false;

**Comment by vaibhavbsharma** [comment]
The right fix for this issue is to run type inference on both the LHS and RHS of the operator being mutated. In this example, we'll want to run type inference on out and also on (a or (b and c)). The type inference will tell us both the sides have the type, bool. Next, we'll want to limit replacement of = with other operators that allow comparison with bool type, e.g. we can replace = with != but not with <, <=, >, >=. 

I think this type inference is separate from the mutation. Writing it outside of the mutation will help us discard not just these invalid ROR mutants but also mutants produced by other mutation operators.

**Comment by sohah** [comment]
Can you tell me which other mutants you are expecting to see typing problems?
